# Generated by Django 5.1.3 on 2024-12-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('igredients', models.TextField()),
                ('description', models.IntegerField()),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('max_students', models.TextField()),
            ],
        ),
    ]
